### ISSUE TITLE
Без лишней необходимости лучше не юзать статики

### ISSUE THREAD

**Issue by coursar** [AlexPshe/netology_service#1]
https://github.com/AlexPshe/netology_service/blob/8039c3d2dca374460e1f18b63fb8d8f69238df09/src/test/java/ru/netology/service/CashbackHackServiceTest.java#L13-L18

1. Сервис достаточно лёгкий
2. С моками потом будет не удобно

**Comment by AlexPshe** [comment]
Поменяла на использование @BeforeEach аннотации.
1. Согласна.
2. Хотелось бы пояснения, в чем именно будет неудобство.

**Comment by coursar** [comment]
Когда студенты будут юзать моки и настраивать их, то получится полная каша, т.к. мок не будет вычищаться для каждого нового теста (static'и не пересоздаются и придётся это делать руками), чего делать не придётся, если всё будет в полях инстанса (т.к. по дефолту JUnit создаёт новый инстанс на каждый тест).

P.S.: И желательно, когда делаете коммиты, относящиеся к какому-либо issue, в сообщении коммита тегать issue: `#1`, тогда в истории сохранится, что вы именно к этому issue сделали коммит.

**Comment by AlexPshe** [comment]
Спасибо за ответ.
Да, я знаю разницу статических полей и нестатических, однако, в данном случае, никаких моков в задании не упоминалось, поэтому я не видела проблемы в использовании статического метода (тем более, что тесты не меняют состояние объекта).

Про коммиты - спасибо, учту.
