### ISSUE TITLE
В assertEquals первый аргумент - expected, второй - actual

### ISSUE THREAD

**Issue by coursar** [AlexPshe/netology_service#2]
https://github.com/AlexPshe/netology_service/blob/55ac5f3cfed3f9a3b0990949c9d267552ce74ca2/src/test/java/ru/netology/service/CashbackHackServiceTest.java#L23

**Comment by coursar** [comment]
Просьба закрыть через [issue closing commit](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords)

**Comment by AlexPshe** [comment]
Good point! Спасибо.
